export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SIGN_UP_USER = 'SIGN_UP_USER'

export const ENABLE_COMPETITION_LOGIN_FLOW = 'ENABLE_COMPETITION_LOGIN_FLOW'
export const DISABLE_COMPETITION_LOGIN_FLOW = 'DISABLE_COMPETITION_LOGIN_FLOW'
export const SET_ACTIVE_COMPETITION = 'SET_ACTIVE_COMPETITION'
